maxlength_block_class_field: 255
field_type: multiple_textfields
default_case: standard
allow_only_letters_and_numbers: false
block_classes_stored:
  - testimonials
  - col-xs-12
  - box4
  - title1
  - col-sm-8
  - nav
  - filters
  - box
  - hidden-xs
  - col-xs-10
  - col-sm-4
  - col-xs-2
  - visible-xs
  - no-fees
  - row
  - col-sm-5
  - col-md-3
  - col-sm-7
  - pull-right
  - full-cta
enable_attributes: true
enable_auto_complete: true
qty_classes_per_block: 10
items_per_page: 50
enable_special_chars: true
qty_attributes_per_block: 10
enable_id_replacement: true
weight_attributes: null
weight_class: null
weight_id: null
maxlength_attributes: 255
attribute_keys_stored: '[]'
attribute_value_stored: '[]'
attributes_inline: '[]'
