_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: classy
defaults:
  sender: php_mail
  formatter: php_mail
modules:
  webform:
    none:
      formatter: webform_php_mail
  smtp:
    none: {  }
  system:
    none: {  }
