_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
langcode: en
smtp_on: false
smtp_host: smtp.staffordshirerealty.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: standard
smtp_autotls: true
smtp_timeout: 30
smtp_username: ''
smtp_password: ''
smtp_from: info@staffordshirerealty.com
smtp_fromname: Staffordshirerealty
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: true
smtp_test_address: ''
smtp_debugging: true
smtp_debug_level: 1
prev_mail_system: php_mail
smtp_keepalive: false
